doctrine:
    dbal:
        driver: '%env(database_driver)%'
        host: '%env(database_host)%'
        port: '%env(int:database_port)%'
        dbname: '%env(database_name)%'
        user: '%env(database_user)%'
        password: '%env(database_password)%'
        server_version: '%env(database_version)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        schema_filter: ~^(?!sessions)~

        types:
            encrypted: 'Gracious\DoctrineEncryptionBundle\Type\Encrypted'
            encryptedJson: 'Mosparo\Doctrine\Type\EncryptedJson'
            encryptedArrayCollection: 'Gracious\DoctrineEncryptionBundle\Type\EncryptedArrayCollection'
            hashed: 'Gracious\DoctrineEncryptionBundle\Type\Hashed'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Mosparo\Entity'
                alias: Mosparo

        filters:
            project_related_filter: Mosparo\Doctrine\ProjectRelatedFilter

