# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(secret)%'
    #csrf_protection: true
    http_method_override: false

    # If you install mosparo behind a reverse proxy, you have to specify the proxy IP address.
    # see https://documentation.mosparo.io/docs/installation/reverse_proxy
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto' ]

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    mailer:
        dsn: '%env(mailer_dsn)%'

        envelope:
            sender: '%env(mailer_from_address)%'

        headers:
            From: '%env(mailer_from_name)% <%env(mailer_from_address)%>'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
